kind: Deployment
apiVersion: apps/v1
metadata:
  name: sensor-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensor-dashboard
  template:
    metadata:
      labels:
        app: sensor-dashboard
    spec:
      containers:
      - name: sensor-dashboard
        image: sensor-dashboard:v1
        resources:
         #cpu and memory limit
          limits:
            memory: "550Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: sensor-dashboard
spec:
  type: LoadBalancer
  selector:
    app: sensor-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
