apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-dashboard
  template:
    metadata:
      labels:
        app: sensor-dashboard
    spec:
      containers:
        - name: sensor-dashboard
          image: groupassignmentregistry.azurecr.io/sensor-dashboard:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            #cpu and memory limit
            limits:
              memory: "550Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sensor-dashboard
spec:
  type: ClusterIP
  selector:
    app: sensor-dashboard
  ports:
    - port: 3000

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sensor-dashboard
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  rules:
    - host: sensor-dashboard.1ebc354abe5745168776.ukwest.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sensor-dashboard
                port:
                  number: 3000
