name: Push

on:
  push:
    branches:
      - "main"

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  STAGING_CLUSTER_NAME: ${{ secrets.STAGING_CLUSTER_NAME }}
  PRODUCTION_CLUSTER_NAME: ${{ secrets.PRODUCTION_CLUSTER_NAME }}
  IMAGE_PULL_SECRET_NAME: ${{ secrets.IMAGE_PULL_SECRET_NAME }}
  STAGING_DEPLOYMENT_MANIFEST_PATH: "deployment-staging.yml"
  PRODUCTION_DEPLOYMENT_MANIFEST_PATH: "deployment-production.yml"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Node.js dependencies
        run: npm ci

      - name: Test
        run: npm test -- --ci --coverage --maxWorkers=2

  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    needs: [run-tests, run-linters]

    outputs:
      imageTag: ${{ steps.generate_tag.outputs.new_tag }}
      imageRepository: ${{ steps.image_repository_op.outputs.image_repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.ECM3440_GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate image repository path
        id: image_repository_op
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo "image_repository=$IMAGE_REPOSITORY" >> $GITHUB_OUTPUT

      - name: Set environment variables
        run: |
          touch .env && echo "REACT_APP_EVENTPROCESSOR_URL=${{ secrets.EVENTPROCESSOR_URL }}" >> .env

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }}  .

      - name: Comment on PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ECM3440_GITHUB_TOKEN }}
        with:
          message: "@${{ github.actor }} Image is available for testing. `docker pull ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}`"
          allow-repeats: false

      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.ECM3440_GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Notify Failure
        if: failure()
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ECM3440_GITHUB_TOKEN }}
        with:
          message: "@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!"
          allow-repeats: false

  create-secret:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[pre-release]')"

    needs: [run-tests, run-linters]

    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.STAGING_CLUSTER_NAME }}

      # Retrieves the credentials for pulling images from your Azure Container Registry
      - name: Get ACR credentials
        id: get-acr-creds
        run: |
          az acr update -n ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} --admin-enabled true
          ACR_USERNAME=$(az acr credential show -g ${{ env.RESOURCE_GROUP }} -n ${{ env.AZURE_CONTAINER_REGISTRY }} --query username -o tsv)
          ACR_PASSWORD=$(az acr credential show -g ${{ env.RESOURCE_GROUP }} -n ${{ env.AZURE_CONTAINER_REGISTRY }} --query passwords[0].value -o tsv)
          echo "::add-mask::${ACR_USERNAME}"
          echo "::set-output name=username::${ACR_USERNAME}"
          echo "::add-mask::${ACR_PASSWORD}"
          echo "::set-output name=password::${ACR_PASSWORD}"

      # Creates a kubernetes secret on your Azure Kubernetes Service cluster that matches up to the credentials from the last step
      - name: Create K8s secret for pulling image from ACR
        uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          container-registry-username: ${{ steps.get-acr-creds.outputs.username }}
          container-registry-password: ${{ steps.get-acr-creds.outputs.password }}
          secret-name: ${{ env.IMAGE_PULL_SECRET_NAME }}

  deploy-staging:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[pre-release]')"

    permissions:
      actions: read
      contents: read
      id-token: write

    needs: [build, create-secret]

    steps:
      # Checks out the repository this file is in
      - name: Checkout
        uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.STAGING_CLUSTER_NAME }}

      - name: Inject environment variables to deployment
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: ${{ env.STAGING_DEPLOYMENT_MANIFEST_PATH }}
          replacement-method: defined
        env:
          SERVICE_NAME: ${{ github.event.repository.name }}
          IMAGE_REPOSITORY: ${{ needs.build.outputs.imageRepository }}
          IMAGE_TAG: ${{ needs.build.outputs.imageTag }}
          INGRESS_HOST: "-staging"

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          manifests: ${{ env.STAGING_DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/ecm3440/sensor-dashboard:${{ needs.build.outputs.imageTag }}
          imagepullsecrets: |
            ${{ env.IMAGE_PULL_SECRET_NAME }}

  deploy-production:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[pre-release]')"

    permissions:
      actions: read
      contents: read
      id-token: write

    needs: [deploy-staging]

    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.ECM3440_GITHUB_TOKEN }}
          approvers: charlie2clarke,Ben-Newman-Exeter
          minimum-approvals: 1
          issue-title: "Deploying ${{ needs.build.outputs.imageTag }} to prod from staging"

      # Checks out the repository this file is in
      - name: Checkout
        uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.PRODUCTION_CLUSTER_NAME }}

      - name: Inject environment variables to deployment
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: ${{ env.PRODUCTION_DEPLOYMENT_MANIFEST_PATH }}
          replacement-method: defined
        env:
          SERVICE_NAME: ${{ github.event.repository.name }}
          IMAGE_REPOSITORY: ${{ needs.build.outputs.imageRepository }}
          IMAGE_TAG: ${{ needs.build.outputs.imageTag }}
          # Setting ingress host to an empty string so that the url will be sensor-dashboard...
          INGRESS_HOST: ""

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          manifests: ${{ env.PRODUCTION_DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/ecm3440/sensor-dashboard:${{ needs.build.outputs.imageTag }}
          imagepullsecrets: |
            ${{ env.IMAGE_PULL_SECRET_NAME }}
